### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=257, address=0x1d447fe82)

### ISSUE THREAD

**Issue by alexgofman** [wibosco/GhostTypewriter#3]
Hey, I get this error in front of topTextLbl.startTypewritingAnimation(completion: nil) 

once I run my app

Could you advise what is the problem? I have followed all instructions

**Comment by wibosco** [comment]
Hey,

I'm happy to help.

Typically `EXC_BAD_ACCESS` happens when you are attempting to access an object which has already been released. It might be useful to add a breakpoint on the `topTextLbl.startTypewritingAnimation(completion: nil)` line and check `topTextLbl` is still valid.

Is your project open source so that you could share it and I could run it myself?

**Comment by alexgofman** [comment]
@wibosco Amazing! 

I fixed the problem by changing class of UILabel in storyboard to TypewriterLabel and module to GhostTypewriter and it works like a charm! 

Thank you very much
